{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "sre-demo.labels" . | nindent 4 }}
    pod-security.kubernetes.io/enforce: {{ .Values.namespace.podSecurityStandard | quote }}
    pod-security.kubernetes.io/audit: {{ .Values.namespace.podSecurityStandard | quote }}
    pod-security.kubernetes.io/warn: {{ .Values.namespace.podSecurityStandard | quote }}
{{- end }}
