{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sre-demo.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sre-demo.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "sre-demo.backendLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sre-demo.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sre-demo.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "sre-demo.frontendLabels" . | nindent 6 }}
{{- end }}
