apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sre-demo.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sre-demo.labels" . | nindent 4 }}
  {{- if .Values.backend.azureMonitor.enabled }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.backend.azureMonitor.clientId | quote }}
  {{- end }}
automountServiceAccountToken: false
