{{- if .Values.serviceMonitor.enabled }}
apiVersion: azmonitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sre-demo.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sre-demo.labels" . | nindent 4 }}
spec:
  labelLimit: 63
  labelNameLengthLimit: 511
  labelValueLengthLimit: 1023
  selector:
    matchLabels:
      {{- include "sre-demo.backendLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout | quote }}
{{- end }}
